import javax.swing.JOptionPane;
public class inicialusuario extends javax.swing.JFrame {

    /**
     * Creates new form inicialusuario
     */
    public inicialusuario(String correo) {
        initComponents();
        sal_nombreusuario.setText(correo);
        setSize(720,450); 
        manguito.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manguito = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entragenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        entraedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        entraestatura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        entrapeso = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        entra_actividad = new javax.swing.JComboBox<>();
        borrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_recomendaciones = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        textocalorias = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textoestadoinicial = new javax.swing.JTextField();
        cerrarsesion = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        sal_nombreusuario = new javax.swing.JLabel();
        txt_estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        manguito.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("Ingresar los datos correctamente");

        jLabel3.setText("Genero:");

        entragenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Femenino", "Masculino" }));

        jLabel4.setText("Edad:");

        jLabel5.setText("Estatura(en cm):");

        jLabel6.setText("Peso(en kg):");

        jLabel7.setText("Tipo de actividad:");

        entra_actividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Sedentario", "Moderado", "Activo" }));

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Recomendaciones:");

        txt_recomendaciones.setEditable(false);
        txt_recomendaciones.setColumns(20);
        txt_recomendaciones.setRows(5);
        jScrollPane1.setViewportView(txt_recomendaciones);

        jLabel9.setText("Calorias Actuales:");

        textocalorias.setEditable(false);

        jLabel10.setText("Indice de masa muscular:");

        jLabel11.setText("En estado de:");

        textoestadoinicial.setEditable(false);

        cerrarsesion.setText("Cerrar Sesion");
        cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarsesionActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioig2.png"))); // NOI18N

        sal_nombreusuario.setText("Nombre Usuario");

        txt_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manguitoLayout = new javax.swing.GroupLayout(manguito);
        manguito.setLayout(manguitoLayout);
        manguitoLayout.setHorizontalGroup(
            manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manguitoLayout.createSequentialGroup()
                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel12))
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(sal_nombreusuario)))
                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entragenero, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entraestatura, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entraedad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entrapeso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entra_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
            .addGroup(manguitoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manguitoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manguitoLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(borrar)
                                .addGap(194, 194, 194))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manguitoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(176, 176, 176))))
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jButton4))
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cerrarsesion)
                                    .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(manguitoLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(80, 80, 80)
                                            .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(manguitoLayout.createSequentialGroup()
                                            .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textocalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textoestadoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );
        manguitoLayout.setVerticalGroup(
            manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manguitoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(entragenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(entraedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(entraestatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(entrapeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(entra_actividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(borrar)))
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(sal_nombreusuario)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manguitoLayout.createSequentialGroup()
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(textocalorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textoestadoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(manguitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manguitoLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manguitoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cerrarsesion))))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );

        getContentPane().add(manguito);
        manguito.setBounds(10, 10, 690, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        String sexo = entragenero.getSelectedItem().toString();
        String actividad = entra_actividad.getSelectedItem().toString();
        String edadStr = entraedad.getText();
        String pesoStr = entrapeso.getText();
        String estaturaStr = entraestatura.getText();

        // Validaciones de campos vacíos
        if (sexo.equals("Seleccionar") || actividad.equals("Seleccionar") ||
            edadStr.isEmpty() || pesoStr.isEmpty() || estaturaStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos deben estar completos.");
            return;
        }

        // Validar que sean números válidos
        int edad = Integer.parseInt(edadStr);
        double peso = Double.parseDouble(pesoStr);
        double estatura = Double.parseDouble(estaturaStr);

        // Validaciones de rangos
        if (edad < 18 || edad > 70) {
            JOptionPane.showMessageDialog(null, "La edad debe estar entre 18 y 70 años.");
            return;
        }

        if (peso < 20) {
            JOptionPane.showMessageDialog(null, "El peso debe ser mayor a 20 kg.");
            return;
        }

        if (estatura < 100 || estatura > 250) {
            JOptionPane.showMessageDialog(null, "La estatura debe estar entre 100 cm y 250 cm.");
            return;
        }

        // Calcular TMB con fórmula de Harris-Benedict
        double tmb;
        if (sexo.equalsIgnoreCase("Masculino")) {
            tmb = 10 * peso + 6.25 * estatura - 5 * edad + 5;
        } else {
            tmb = 10 * peso + 6.25 * estatura - 5 * edad - 161;
        }

        // Factor de actividad
        double factorActividad = switch (actividad.toLowerCase()) {
            case "sedentario" -> 1.2;
            case "moderado" -> 1.55;
            case "activo" -> 1.9;
            default -> 1.0;
        };

        double calorias = tmb * factorActividad;

        // Calcular IMC
        double estaturaM = estatura / 100; // pasar a metros
        double imc = peso / (estaturaM * estaturaM);

        String estado;
        if (imc < 18.5) {
            estado = "Bajo peso";
        } else if (imc < 24.9) {
            estado = "Normal";
        } else if (imc < 29.9) {
            estado = "Sobrepeso";
        } else {
            estado = "Obesidad";
        }

        // Recomendaciones personalizadas
        String recomendacion = switch (actividad.toLowerCase()) {
            case "sedentario" -> """
                • Intenta caminar 30 minutos al día, incluso si es en casa o cerca.
                • Evita comidas rápidas y procesadas. Prefiere vegetales, frutas y agua.
                • Prueba hobbies relajantes como leer, escuchar música o colorear.
                """;
            case "moderado" -> """
                • Sigue con tu rutina, pero añade algo diferente como yoga o bicicleta.
                • Come proteínas magras como pollo, huevos, legumbres y arroz integral.
                • Puedes explorar hobbies como la fotografía o salir a caminar en la naturaleza.
                """;
            case "activo" -> """
                • ¡Sigue así! Incluye días de descanso o actividades suaves como estiramiento.
                • Incrementa tus snacks saludables: nueces, yogur griego, batidos naturales.
                • Aprovecha tu energía para explorar nuevos deportes o voluntariados físicos.
                """;
            default -> "Selecciona un tipo de actividad válido.";
        };

        // Mostrar resultados
        textocalorias.setText(String.format("%.2f", calorias));
        textoestadoinicial.setText(String.format("%.2f", imc));
        txt_estado.setText(estado);
        txt_recomendaciones.setText(recomendacion);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Por favor, introduce valores numéricos válidos.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocurrió un error: " + e.getMessage());
    }        
      
            
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarsesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas cerrar sesión?", "Confirmar cierre de sesión", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        this.dispose(); 
        new pag1().setVisible(true);
      
    }
    }//GEN-LAST:event_cerrarsesionActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
          entragenero.setSelectedIndex(0);
    entra_actividad.setSelectedIndex(0);
    entraedad.setText("");
    entrapeso.setText("");
    entraestatura.setText("");
    
    
    }//GEN-LAST:event_borrarActionPerformed

    private void txt_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estadoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        textocalorias.setText("");
    textoestadoinicial.setText("");
    txt_estado.setText("");
    txt_recomendaciones.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicialusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicialusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicialusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicialusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pag1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton cerrarsesion;
    private javax.swing.JComboBox<String> entra_actividad;
    private javax.swing.JTextField entraedad;
    private javax.swing.JTextField entraestatura;
    private javax.swing.JComboBox<String> entragenero;
    private javax.swing.JTextField entrapeso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel manguito;
    private javax.swing.JLabel sal_nombreusuario;
    private javax.swing.JTextField textocalorias;
    private javax.swing.JTextField textoestadoinicial;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextArea txt_recomendaciones;
    // End of variables declaration//GEN-END:variables
}
