
import javax.swing.JOptionPane;

public class pag1 extends javax.swing.JFrame {

    /**
     * Creates new form pag1
     */
    public pag1() {
        initComponents();
        setSize(720, 440);
        manzana.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manzana = new javax.swing.JPanel();
        btn_iniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        entra_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        entra_contraseña = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        manzana.setBackground(new java.awt.Color(255, 255, 255));
        manzana.setOpaque(false);

        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Iniciar Sesion");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Email");

        entra_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entra_emailActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        entra_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entra_contraseñaActionPerformed(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Eres nuevo?");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Soy Coordinador");

        jButton3.setText("Iniciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manzanaLayout = new javax.swing.GroupLayout(manzana);
        manzana.setLayout(manzanaLayout);
        manzanaLayout.setHorizontalGroup(
            manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manzanaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
            .addGroup(manzanaLayout.createSequentialGroup()
                .addGroup(manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manzanaLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel3))
                    .addGroup(manzanaLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_iniciar)
                            .addGroup(manzanaLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))))
                    .addGroup(manzanaLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entra_email)
                            .addComponent(entra_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                    .addGroup(manzanaLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manzanaLayout.setVerticalGroup(
            manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manzanaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entra_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(entra_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btn_iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(manzanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        getContentPane().add(manzana);
        manzana.setBounds(30, 20, 664, 395);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 710, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entra_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entra_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entra_emailActionPerformed

    private void entra_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entra_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entra_contraseñaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new logincoor().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed

        String correo = entra_email.getText();
        String pass = entra_contraseña.getText();
        boolean encontrado = false;

        for (Usuario u : ArrayListUsuarios.listaUsuarios) {
            if (u.getCorreo().equals(correo) && u.getContraseña().equals(pass)) {
    encontrado = true;

    String tipo = u.getTipoUsuario();

    if (tipo.equals("Usuario Normal")) {
        JOptionPane.showMessageDialog(this, "¡Bienvenido usuario " + u.getNombre() + "!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        new Formu2(u).setVisible(true);
    } else if (tipo.equals("Coordinador")) {
        JOptionPane.showMessageDialog(this, "¡Bienvenido coordinador " + u.getNombre() + "!", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }

    this.dispose();
    break;
}
        }
        
       

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    String correo = JOptionPane.showInputDialog("Nuevo correo:");
    String contraseña = JOptionPane.showInputDialog("Nueva contraseña");
    if (correo == null || correo.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Registro cancelado o correo vacio");
        return;
    }

    Usuario nuevoUsuario = new UsuarioNormal(correo, contraseña);
    ArrayListUsuarios.listaUsuarios.add(nuevoUsuario);

    JOptionPane.showMessageDialog(null, "Usuario registrado correctamente");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pag1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pag1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JTextField entra_contraseña;
    private javax.swing.JTextField entra_email;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel manzana;
    // End of variables declaration//GEN-END:variables
}
